### ISSUE TITLE
Please help me with this cuda error :: Using anaconda

### ISSUE THREAD

**Issue by iamharnek** [xiadingZ/video-caption-pytorch#39]
(base) C:\Users\harne\Downloads\video-caption.pytorch-master> python prepro_feats.py --output_dir data/feats/resnet152 --model resnet152 --n_frame_steps 40  --gpu 4,5
THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=50 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "prepro_feats.py", line 106, in <module>
    model = model.cuda()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 311, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 208, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 208, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 230, in _apply
    param_applied = fn(param)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 311, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 179, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:50

**Comment by holibert** [comment]
I encounter the RuntimeError: CUDNN_STATUS_EXECUTE"_FAILED. I fixed it by changing the run evironment as follows:
pytorch 0.4.1
CUDA9.0
cudnn7.6.5
python3.6
It maybe help you.
